{% set version = "1.2.1" %}
{% set sha256 = "fe89189ef392bfb7a6eacc2eb79728de9e3bfd130af3b10d09c62c221f656a74" %}

package:
  name: depfinder
  version: {{ version }}

source:
  fn: depfinder-{{ version }}.tar.gz
  url: https://github.com/ericdill/depfinder/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - stdlib-list
    - pyyaml

test:
  commands:
    - depfinder -h
  imports:
    - depfinder

about:
  home: http://github.com/ericdill/depfinder
  license: BSD 3-Clause
  summary: Find all the unique imports in your library 

extra:
  recipe-maintainers:
    - ericdill
    - mariusvniekerk
