{% set version = "2.8.1" %}

package:
  name: depfinder
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/depfinder-{{ version }}.tar.gz
  sha256: 5d80bce796ea7a1994fb888ac4056e5ff9d2b390d7d656e75c45eedaef916090

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - depfinder = depfinder.cli:cli

requirements:
  host:
    - python >=3.6,<3.10
    - pip
  run:
    - python >=3.6,<3.10
    - pyyaml
    - requests
    - stdlib-list

test:
  imports:
    - depfinder
  commands:
    - pip check
    - depfinder --help
  requires:
    - pip

about:
  home: http://github.com/ericdill/depfinder
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Find all the unique imports in your library

extra:
  recipe-maintainers:
    - ericdill
    - mariusvniekerk
    - tonyfast
    - ocefpaf
    - CJ-Wright
    - beckermr
