{% set version = "2.2.1" %}
{% set sha256 = "720c96b5dca5222b92836cf9422b39ec01a19ea4df91085d78b13439cec18ae6" %}
{% set name = "depfinder" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - depfinder = depfinder.cli:cli

requirements:
  host:
    - pip
    - python <3.7
    - setuptools
  run:
    # stdlib-list is not yet py37 compatible https://github.com/ericdill/depfinder/issues/20
    - python <3.7
    - stdlib-list
    - pyyaml

test:
  commands:
    - depfinder -h
  imports:
    - depfinder

about:
  home: http://github.com/ericdill/depfinder
  license: BSD 3-Clause
  license_file: LICENSE
  summary: Find all the unique imports in your library

extra:
  recipe-maintainers:
    - ericdill
    - mariusvniekerk
    - tonyfast
    - ocefpaf
