{% set version = "2.7.1" %}

package:
  name: depfinder
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/depfinder/depfinder-{{ version }}.tar.gz
  sha256: 2256a4cadb8e0e6107bbff31e34c35de89ea297789ea97df3c6bb3acce8f4081

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - depfinder = depfinder.cli:cli

requirements:
  host:
    - python
    - pip
  run:
    - python
    - stdlib-list
    - pyyaml

test:
  commands:
    - depfinder -h
  imports:
    - depfinder

about:
  home: http://github.com/ericdill/depfinder
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Find all the unique imports in your library

extra:
  recipe-maintainers:
    - ericdill
    - mariusvniekerk
    - tonyfast
    - ocefpaf
    - CJ-Wright
